server:
#  address: 127.0.0.1
  port: 9000
spring:
  resources:
    static-locations: classpath:templates/,classpath:javadoc/,classpath:js/
#  mvc:
#    view:
#      suffix: .html
#      prefix: javadoc/
#    static-path-pattern: /javadoc/**